### ISSUE TITLE
The latest released version (0.70.0) does not build with the latest release of SZ (2.1.11.2)

### ISSUE THREAD

**Issue by valmar** [robertu94/libpressio#21]
I just would like to report that trying to build the latest release (0.70.0) against the latest release of SZ (2.1.11.2) results in the following error:

```
[ 86%] Building CXX object CMakeFiles/libpressio.dir/src/plugins/compressors/sz_plugin.cc.o
[ 88%] Building CXX object CMakeFiles/libpressio.dir/src/plugins/compressors/sz_omp.cc.o
[ 89%] Building CXX object CMakeFiles/libpressio.dir/src/plugins/compressors/sz_threadsafe_plugin.cc.o
[ 91%] Building CXX object CMakeFiles/libpressio.dir/src/plugins/compressors/sz_common.cc.o
/home/conda/feedstock_root/build_artifacts/libpressio_1626800045112/work/src/plugins/compressors/sz_threadsafe_plugin.cc: In member function 'virtual int sz_threadsafe_plugin::compress_impl(const pressio_data*, pressio_data*)':
/home/conda/feedstock_root/build_artifacts/libpressio_1626800045112/work/src/plugins/compressors/sz_threadsafe_plugin.cc:267:36: error: 'SZ_compress_customize_threadsafe' was not declared in this scope; did you mean 'SZ_compress_customize'?
  267 |     unsigned char* compressed_data=SZ_compress_customize_threadsafe(app.c_str(),user_params,libpressio_type_to_sz_type(input->dtype()),input->data(),
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    SZ_compress_customize
/home/conda/feedstock_root/build_artifacts/libpressio_1626800045112/work/src/plugins/compressors/sz_threadsafe_plugin.cc: In member function 'virtual int sz_threadsafe_plugin::decompress_impl(const pressio_data*, pressio_data*)':
/home/conda/feedstock_root/build_artifacts/libpressio_1626800045112/work/src/plugins/compressors/sz_threadsafe_plugin.cc:291:29: error: 'SZ_decompress_customize_threadsafe' was not declared in this scope; did you mean 'SZ_decompress_customize'?
  291 |     void* decompressed_data=SZ_decompress_customize_threadsafe(
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                             SZ_decompress_customize
make[2]: *** [CMakeFiles/libpressio.dir/build.make:790: CMakeFiles/libpressio.dir/src/plugins/compressors/sz_threadsafe_plugin.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/libpressio.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2191, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/libpressio_1626800045112/work/conda_build.sh']' returned non-zero exit status 2.
```

Thank you for your help

**Comment by robertu94** [comment]
@valmar Sorry, SZ added these functions to the latest master branch, but there hasn't been a release yet.  LibPressio post 0.70.0 depends on these functions to provide threadsafe sz compression which yields considerable performance improvements.

**Comment by valmar** [comment]
@robertu94 Thank you very much for your quick answer. Do you have a connection with the SZ developers? Maybe we can ask them to at least tag the branch? It would make life much easier for our automated building pipeline

**Comment by robertu94** [comment]
@valmar I spoke to the lead SZ developer @disheng222 about this a few days ago, and I expect he will get to it soon.

**Comment by valmar** [comment]
@robertu94 Thank you so much!

**Comment by robertu94** [comment]
@valmar SZ 2.1.12 is now released.

**Comment by valmar** [comment]
Thank you!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
